@Axxes.EfCore.Workshop.API_HostAddress = http://localhost:5254

POST {{Axxes.EfCore.Workshop.API_HostAddress}}/Movie/
Content-Type: application/json

{
  "title": "Fight Club",
  "releaseDate": "1999-02-11",
  "description": "Ed Norton and Brad Pitt fight for a bit.",
  "boxOfficeRevenue" : 1000000.0,
  "directors": [{
    "firstName": "David",
    "lastName": "Fincher"
  }]
}
###

GET {{Axxes.EfCore.Workshop.API_HostAddress}}/Movie/8
Accept: application/json

###
